name: Deploy to Test Environment

on:
  pull_request:
    types: [labeled]

env:
  AWS_REGION: sa-east-1

jobs:
  build:
    if: contains( github.event.label.name, 'Deploy to Test Environment')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.1]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn install
        run: |
          yarn install
      - name: Yarn build
        run: |
          yarn build
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ env.AWS_TEST_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEPLOY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEPLOY }}
          AWS_REGION: ${{ env.AWS_REGION }}
          SOURCE_DIR: "build"
